Add documentation about controlplane endpoint and IPAM
nutanix-cloud-native/opendocs pull request #10
Opened 2022-11-08 13:29 UTC by yannickstruyf3

Add documentation about controlplane endpoint and IPAM
Modified versioning of CAPX docs

2022-11-08 13:56 UTC, tuxtof approved these changes

2022-11-10 11:55 UTC, vnephologist requested changes
“assignations” should be “assignments”

2022-11-10 11:59 UTC, yannickstruyf3 commented
> 

modified

2022-11-10 12:03 UTC, vnephologist approved these changes
Lgtm

2022-11-10 12:03 UTC, merged